#+TITLE: Network Protocols

* Internet of Strings
** Two parties connected by a string and each have a pad and a piece of paper. How do they communicate?
   * The two parties could send a note on the string to each other. 
   * Provide some information. But you don't need a ton of metadata to send it to just one person on the string
   * Multiple people on the end of the strings would require more metadata, saying who you are and who the message is intended for.
   * Each party might want to use a different way of messaging. Different methods of communication over the same link. This info could be provided at the top somewhere.
   * Sending large info across the string would require you to send a small amount of data at a time. Break up the message. The person on the other end will need to reassemble the message. There has to be some kind of method to do that.
** Three Parties: How do they communicate?
   * Specify the group in the middle to pass it along to the next group.
   * The middle group doesn't need to know everything about the other group, they just need to know what messages to send to them for them to organize.
   * You might need to use encryption if you don't want the middle group to be able to read the message. You may also want to make sure the message is delivered safely and untampered.
   * You may need to consider things like distance, speed, amount of data, integrity, redundance, etc. These are things to consider when dealing with network protocols.

* Postal mail analogy vs. Sending a Packet
+ Address is like an IP address. 
  * DNS is like a phone book that finds all the addresses of that you need
+ Post Office is like the local router
+ Zip code is like the network part of an IP address.
+ Routing list is like a routing table
  * They know the next hop, not the full route
+ Mail Carrier delivers to the recipient using the street address 
  * Uses host part of IP address and MAC address to send to the machine on the local router 

* Network Protocols 
- Defines rules and convention for communication between network devices. 
  - Mechanisms for devices to identify and make connections with each other
  - Rules for how packages are sent and recieved
- One universal protocol for all data is inefficient 
  - What happens if we move to wireless from wired? Now wee need to alter to support wireless as well. 
    Bloated
  - Network devs developed modular protocols that focus on certain specific aspects
- Use several protocols in a single session.
  - Might use HTTP which is built on TCP which is built on IP, etc. 
  - Depends on the layer. Each layer could use a specific protocol
- Protocols are used in layers to manage the complexities 
  - One universal protocol has to know everything. Dividing up to layers helps us concentrate on a specific part of communication at a time.
- Types of layerd models
  - Protocol Model:
    Specify specific protocols. TCP/IP uses TCP/IP
  - Refrence Model:
    OSI model for example. Ambiguous. 
  - OSI Model has 7 layers while the TCP/IP combines the last 4 layers. Web traffic is focused on Application.
    Sometimes TCP has two physical layers, splitting data link and physical. 
- Protocol Suite:
  - Specific set of protocols that work together. TCP/IP, bluetooth
- Layering model:
  - Helps manage system complexity for protocol designers and implementers.
  - Only have to focus on specific steps at each layer
  - Assists in protocol design. Only have to focus on a single layer when working on a specific protocol
  - Provides a common language and fosters competition/collaboration
  - Most common models are the OSI model and the TCP/IP model
- Networking Models:
  - Protocol Model:
    - Model closely matches the structure of a particular protocol suite.
  - Refrence Model:
    - An ambiguous structure such as the OSI model
* OSI Model
- Network protocol framework in 7 layers that define how data can travel between computers
  1. Physical
     * How we are sending bits over media. Wires, fiber optic, radio waves, etc.
     * How bits are sent between nodes
       * Radio frequency, etc
  2. Datalink
     * Direct addressing, MAC addresses, how does traffic travel, prevent clashing, etc.
     * Giving the letter to the post office, for the letter analogy
     * Node to node data transfer from two connected nodes
       * Network card to another network card.
       * MAC addresses
  3. Network
     * IP addresses of sender/reciever
     * How communication actually happens
       * Logical addressing system (IP addressing)
       * How packets are routed and forwarded
  4. Transport
     * Multiplex traffic on computers and what kind of ports we are using.
     * Port 80 deals with HTTP traffic
     * Port 443 deals with HTTPS traffic
     * Where or what program on thee machine sends the data
       * Make sure all the data is recieved in the correct order
  5. Session
     * Session set up and teardown
     * TCP uses handshakes to establish connections. This kind of like layer 5 work (? maybe??)
     * Setup and Termination of a connection between applications.
       * How long we wait for a response, how to setup a connection, etc
  6. Presentation
     * Compression, enctyption, other encoding
     * What kind of code is it using? etc
     * "Presents" data for the application or the network
       * Encryption/decryption or compression. Encoding.
  7. Application
     * Data that we are sending to destination device.
     * Body of the letter if we want to use the letter analogy
     * Closest to the user
       * protocols for file transfer, email, web browsing
- This goes up the layer (generally is listed 7 down) 
- Encapsulation: 
      Wrapping data in the application process and adding headers that specify what to do at each layer.
- Data might go up and down layer 3-1 a few times as it hits a few routers
- This model gives up a nice visual represnentation on how networking is supposed to work
- Helps troubleshoot
- Helps developers work on developing certain programs
- Advertisement to how a program works 
- Please Do Not Throw Sausage Pizza Away

* TCP/IP Model
* Wireshark
- Software to capture packets on a certain network device and network
- Top will show all the packets captured and some basic details. Clicking will show more data about headers in the middle window
  - The top window can add filters and ways to make it easier to parse through the data and find what you are looking for.
- No specific layer 1 header, but the same info can be found in the Frame header 
- Bottom will show the data of that packet based on the headers
  - You can see the raw bytes of specific headers by clicking on the header in the middle window. This will change what is displayed on the bottom window.
* Packet Headers  
** How data moves through layers:
   * Protocols that have a layer have to pass data through layers of protocols on the sender machine and the reciever machine
** Headers
   * Extra information that is added to a packet by the sender that is used by the reciever
   * information is added by each layer
     - Physical layer doesn't add information often
   * Encapsulation is the process of a packet being "wrapped" in headers
   * Information (headers) gets removed by the recieving machine to get to the packet
** Headers from each layer on the TCP model
   * Physical (Osi 1)
     - Specify details about transmission detail (wifi, hardware)
   * Network Interface Layer (TCP/IP Layer 1)
     - Details about communication between higher layers of protocols.
** Footer
   * Just everything at the very end

* Network Models
** Network Protocols
   * Defines rules and conventions for communication between network devices
   * ways for devices to identify and make connections (addressing)
   * Formatting rules
   * Rules on how packets are sent and recieved
   See [[Network Protocols]]
** Layer Models
   * Assists in protocol design.
     * If you are writing a protocol, you know what layers you will have to work with.
   * "Fosters Competition" or how Reeves puts it, "Fosters Collaboration"
     * Your solutions will have to work with those in the layers above and below yours
   * Prevents compatability changes in one layer from affecting the ones in the others.
     * You don't have to care about the addressing solution if you are working Application.
     * You assume that the layers below yours are working properly with the ones around it so it works with the ones around yours
   * Common language
** OSI vs TCP/IP
   * 7 Layers vs 5 Layers
   * OSI Layers: See [[OSI Model]]
   * TCP/IP Layers: See [[TCP/IP]]
     
* Ethernet and ARP
** What is Ethernet?
   * Not the cable
   * A communication paradigm/protocol
   * Check line, if clear, send message
   * 2 computers sending at a time can cause a collision
   * Needs to know where it's going, where data is going, what to do with data
     * Source Address, Destination Address, "EtherType" Field
   * Header is 14 bytes, 6 for destination, 6 for source, 2 for "EtherType"
   * MAC Addresses
     * 6 bytes
       * First 3 are OUI (Manufacturer)
         * Identify the NIC, not nessesarily the whole product
       * Last 3 are the "uniquely" identify the device
         * They don't really, but try
   * Type Field: What value is coming next EtherType
     * 0x0800 IPV4
     * 0x06DD IPV6
     * 0x0806 is ARP
** Address Resolution
   * Request is sent using IP one hop at a time physical networks.
   * At each hop, a transmission occurs using MAC addresses
   * ARP gives us the MACs of the devices that we need to hop to
   * ARP Order:
     1. Begins when a source device on an IP network needs to send a piece of IP data
     2. Decides where it needs to go, either distant or local
     3. If local, it ask in a broadcast for the MAC
     4. If distant, it asks for the default gateway's MAC
   * ARP has a specificy format that includes information on the MACs, the lengths, the sender IP, and the target IP
   * There is no footer.
   * ARP is kind of inefficient every time, so we have an ARP cache for recent MAC addresses we just looked up.
   * Cache expires if not used for a little bit.
   * ARP kind of lacks some security. There is no verification, leaving it vulnerable to certain attacks
   * A footer might be included if the packet does not meet a minimum length requirnment. 
*** Chapter 13 Notes
    * Every device with a full featured network stack should have addresses at layer 2 and 3. Address resolution is what links the two together.
    * Addressing is done at two layers because they are different serve different purposes.
    * Layer 2 addresses work on local transmissions between devices that can communicate directly
    * Layer 3 addresses internetwork to create something similar to a large virtual network at the network layer
    * Even devices that communicate logically on the IP layer, but must also be accompolished in the data link
      * You must translate. This is address resolution
**** Direct Mapping
     * You take a scheme from the layer 2 and 3 address and determine one from the other using a simple algorithm
     * This only works when the data link layer address is a functino of the network layer address
     * impossible when the layer 2 address is larger than the layer 3 address
**** Dynamic Address Resolution
     * simple and highly efficient
     * This involves bullying other devices on the network for information on the layer 2 address that corresponds with the layer 3 address
     * Removes the restrictions from direct mapping
     * Invovles an extra message than direct mapping does and requires a broadcast message that is sent to everyone.
       * This is resolved with a chaching mechanism
**** ARP
     * Dynamic resolution protocol that matches IP addresses to data link addresses. Originally written for Ethernet, but allowed IP to work over layer 2 technologies
     * In IP, Ethernet addresses are 48 bits while IP was 32, ruling out direct mapping
     * Basic ARP is as follows:
       1) Source device has an IP data-gram and needs to determine if it's on the local network or a distant network
       2) If it's the former, it will send it directly to the destination
       3) After packaging it, it sends it to it's ARP software for address resolution
     * General Operation is as follows:
       1) Check ARP cache for destination hardware address
       2) Generate ARP request frame
       3) Broadcast ARP request frame
       4) Destination recieves and processes request frame
       5) Generates ARP reply frame
       6) Updates ARP cache
       7) Sends the ARP Reply Frame
       8) Source recieves the reply frame
       9) Updates ARP cache
     * Has 9 fields in a message
** Attacks
   * MAC spoofing. Easy way to mimic MAC of a different machine
   * We can bypass MAC-based network controls
     * MAC restrictions can just be subverted
   * ARP spoofing: Convincing a sender that you are the intended reciever.
     * You dont need to spoof a MAC, you just have to spoof an ARP response.
     * This results in a MITM attack
   * Gratuitous ARP: ARP Reply that was never requested. 
   * DoS Attack
   * MITM Attack
   * Session Hijacking
   * This is all Layer 2, so you have to be on the same local network to be vulnerable to this attack
*** Protecting against ARP spoofing
    * MAC-To-Port mappings at the switch level so you have to be hardwired 
    * Static IP-to-MAC mappings, so every MAC has a specified IP address assigned to it.
    * Dynamic ARP inspection.
      * Spies on DHCP traffic and builds a table between each MAC/IP/Port. The switch will throw away packets that don't fit the trend
  

* Routing Tables
  * Determines where to send a packet
  * Requires the following info:
    1. Network Address
    2. Subnet Mask
    3. Next Hop
    4. Interface
  * A router that connects two networks will need routing table entries for information between the two routers
  * Are not bound to just that info, can have Distance (number of hops) or Prefrence (if it has multiple ways to get somewhere)
  * A router does not need to know the entire path just the next hop
  * A CAM table for a switch will have the Host, MAC, and port
* IP
  * The most common layer 3 protocol
  * Does a few important funtions:
    * Addressing
      * identify both the network address as well as the host address of the device interface
    * Routing/Indirect Delivery
      * final destination is often distant
      * NIC to NIC (layer 2 transmission) wont work in this case
      * Datagram must be sent indirectly by sending it to the next hop
    * Fragmentation and Reassembly
      * Layer 1 and 2 have maximum frame size
      * Can splits datagrams into pieces for easier transmission
      * the destination machine will reassemble the packet to recreate the whole datagram
    * TTL (Time To Live)
      * Important as packets could end up floating forever if it never reaches it's destination
      * TTL decreases by one at every hop
** IP Header
   * Version
     * 4 or 6
   * Header length
     * Just the header
   * Protocol
     * for example, 1 is ICMP, 6 is TCP, or 17 is UDP
   * Total Length
     * The entire IP datagram or packet
   * Fragmentation Offset
     * The order of the fragments to put it back together
   * IP Flags
   * Header Checksum
   * RFC 791

* ICMP
  * Internet Control Messaging Protocol
  * Generally just carries system messages such as ping
  * Contains messages that report errors or messages to obtain information
    * Echo Request and Echo Reply
  * Errors
    * Time exceeded or Destination unreachable 
      * TTL Expires
